//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstituteEntities : DbContext
    {
        public InstituteEntities()
            : base("name=InstituteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<tblCamarero> tblCamareroes { get; set; }
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblCocinero> tblCocineroes { get; set; }
        public virtual DbSet<tblDetalleFactura> tblDetalleFacturas { get; set; }
        public virtual DbSet<tblFactura> tblFacturas { get; set; }
        public virtual DbSet<tblMesa> tblMesas { get; set; }
    }
}
