//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetalleFactura
    {
        public int IdDetalleFactura { get; set; }
        public int IdFactura { get; set; }
        public int IdCocinero { get; set; }
        public string Plato { get; set; }
        public decimal Importe { get; set; }
    
        public virtual tblCocinero tblCocinero { get; set; }
        public virtual tblFactura tblFactura { get; set; }
    }
}
