//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFactura()
        {
            this.tblDetalleFacturas = new HashSet<tblDetalleFactura>();
        }
    
        public int IdFactura { get; set; }
        public int IdCliente { get; set; }
        public int IdCamarero { get; set; }
        public int IdMesa { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
    
        public virtual tblCamarero tblCamarero { get; set; }
        public virtual tblCliente tblCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetalleFactura> tblDetalleFacturas { get; set; }
        public virtual tblMesa tblMesa { get; set; }
    }
}
